import { OfflineSigner } from '@cosmjs/proto-signing';
import { SigningCosmWasmClient } from '@cosmjs/cosmwasm-stargate';
import { SigningStargateClient } from '@cosmjs/stargate';
import { Wallet, ManagerActions, WalletData, SignerOptions, ChainRecord, EndpointOptions } from './types';
import { Actions, ViewOptions, ChainName, WalletName, WalletAdapter } from './types';
import { StateBase } from './bases';
import { Chain } from '@chain-registry/types';
export declare class WalletManager extends StateBase<WalletData> {
    protected _currentWalletName?: WalletName;
    protected _currentChainName?: ChainName;
    protected _useView: boolean;
    protected _concurrency?: number;
    actions?: ManagerActions<WalletData>;
    wallets: Wallet[];
    chains: ChainRecord[];
    viewOptions: ViewOptions;
    constructor(chains?: Chain[], wallets?: Wallet[], signerOptions?: SignerOptions, viewOptions?: ViewOptions, endpointOptions?: EndpointOptions, _concurrency?: number);
    get useView(): boolean;
    get currentWalletName(): string;
    get currentChainName(): string;
    get currentWallet(): WalletAdapter | undefined;
    get data(): WalletData;
    get state(): import("./types").State;
    get message(): string;
    get username(): string | undefined;
    get address(): string | undefined;
    get offlineSigner(): OfflineSigner | undefined;
    get walletNames(): string[];
    get walletCount(): number;
    get chainNames(): string[];
    get chainCount(): number;
    get concurrency(): number;
    emit(type: string): import("./types").Dispatch<unknown>;
    get emitWalletName(): import("./types").Dispatch<string>;
    get emitChainName(): import("./types").Dispatch<string>;
    get emitViewOpen(): import("./types").Dispatch<boolean>;
    getStargateClient: () => Promise<SigningStargateClient | undefined>;
    getCosmWasmClient: () => Promise<SigningCosmWasmClient | undefined>;
    setActions(actions: Actions): void;
    setViewOptions(viewOptions: ViewOptions): void;
    reset(): void;
    setCurrentWallet: (walletName?: WalletName) => void;
    setCurrentChain: (chainName?: ChainName) => void;
    private getWallet;
    update: () => void;
    connect: () => Promise<void>;
    disconnect: () => Promise<void>;
    openView: () => void;
    closeView: () => void;
}
