import { AssetList, Chain } from '@chain-registry/types';
import { CosmWasmClient, SigningCosmWasmClient } from '@cosmjs/cosmwasm-stargate';
import { EncodeObject, OfflineSigner } from '@cosmjs/proto-signing';
import { SigningStargateClient, StargateClient, StdFee } from '@cosmjs/stargate';
import { TxRaw } from 'cosmjs-types/cosmos/tx/v1beta1/tx';
import { MainWalletBase, StateBase } from './bases';
import { ChainName, ChainRecord, CosmosClientType, EndpointOptions, ManagerActions, SessionOptions, SignerOptions, State, StorageOptions, ViewOptions, Wallet, WalletAdapter, WalletData, WalletName } from './types';
export declare class WalletManager extends StateBase<WalletData> {
    private _currentWalletName?;
    private _currentChainName?;
    actions?: ManagerActions<WalletData>;
    private _activeWallets;
    private _totalWallets;
    private _chainRecords;
    viewOptions: ViewOptions;
    storageOptions: StorageOptions;
    sessionOptions: SessionOptions;
    constructor(chains: Chain[], assetLists: AssetList[], wallets: MainWalletBase[], signerOptions?: SignerOptions, viewOptions?: ViewOptions, endpointOptions?: EndpointOptions, storageOptions?: StorageOptions, sessionOptions?: SessionOptions);
    setChains: (chains: Chain[], assetLists: AssetList[], signerOptions?: SignerOptions, endpointOptions?: EndpointOptions) => void;
    setWallets: (wallets: MainWalletBase[]) => void;
    setActiveWalletNames: (walletNames?: WalletName[]) => void;
    get wallets(): MainWalletBase[];
    get chainRecords(): ChainRecord[];
    get useStorage(): boolean;
    get currentWalletName(): string;
    get currentChainName(): string;
    get currentWallet(): WalletAdapter | undefined;
    get currentWalletInfo(): Wallet | undefined;
    get currentChainRecord(): ChainRecord | undefined;
    get data(): WalletData | undefined;
    get state(): State;
    get message(): string;
    get username(): string | undefined;
    get address(): string | undefined;
    get offlineSigner(): OfflineSigner | undefined;
    get walletNames(): string[];
    get walletCount(): number;
    get chainNames(): string[];
    get chainCount(): number;
    private get emitWalletName();
    private get emitChainName();
    private get emitViewOpen();
    enable: (chainIds: string | string[]) => Promise<void>;
    getRpcEndpoint: () => Promise<string | undefined>;
    getRestEndpoint: () => Promise<string | undefined>;
    getStargateClient: () => Promise<StargateClient | undefined>;
    getCosmWasmClient: () => Promise<CosmWasmClient | undefined>;
    getSigningStargateClient: () => Promise<SigningStargateClient | undefined>;
    getSigningCosmWasmClient: () => Promise<SigningCosmWasmClient | undefined>;
    sign: (messages: EncodeObject[], fee: StdFee, memo?: string, type?: CosmosClientType) => Promise<TxRaw>;
    broadcast: (signedMessages: TxRaw, type?: CosmosClientType) => Promise<import("@cosmjs/stargate").DeliverTxResponse>;
    signAndBroadcast: (messages: EncodeObject[], fee?: StdFee, memo?: string, type?: CosmosClientType) => Promise<import("@cosmjs/stargate").DeliverTxResponse>;
    reset: () => void;
    private updateLocalStorage;
    setCurrentWallet: (walletName?: WalletName) => void;
    setCurrentChain: (chainName?: ChainName) => void;
    getWallet: (walletName: WalletName, chainName?: ChainName) => WalletAdapter;
    getChainRecord: (chainName?: ChainName) => ChainRecord | undefined;
    getChainLogo: (chainName?: ChainName) => string | undefined;
    private get callbacks();
    connect: () => Promise<void>;
    disconnect: () => Promise<void>;
    openView: () => void;
    closeView: () => void;
    private _handleTabLoad;
    private _handleTabClose;
    private _connectEventListener;
    onMounted: () => void;
    onUnmounted: () => void;
}
