import { AssetList, Chain } from '@chain-registry/types';
import { SigningCosmWasmClient } from '@cosmjs/cosmwasm-stargate';
import { OfflineSigner } from '@cosmjs/proto-signing';
import { SigningStargateClient } from '@cosmjs/stargate';
import { StateBase } from './bases';
import { Actions, ChainName, ChainRecord, EndpointOptions, ManagerActions, SessionOptions, SignerOptions, State, StorageOptions, ViewOptions, WalletAdapter, WalletData, WalletName, WalletOption } from './types';
export declare class WalletManager extends StateBase<WalletData> {
    protected _currentWalletName?: WalletName;
    protected _currentChainName?: ChainName;
    actions?: ManagerActions<WalletData>;
    wallets: WalletOption[];
    chains: ChainRecord[];
    viewOptions: ViewOptions;
    storageOptions: StorageOptions;
    sessionOptions: SessionOptions;
    constructor(chains: Chain[], assetLists: AssetList[], wallets: WalletOption[], signerOptions?: SignerOptions, viewOptions?: ViewOptions, endpointOptions?: EndpointOptions, storageOptions?: StorageOptions, sessionOptions?: SessionOptions);
    get useStorage(): boolean;
    get currentWalletName(): string;
    get currentChainName(): string;
    get currentWallet(): WalletAdapter | undefined;
    get data(): WalletData | undefined;
    get state(): State;
    get message(): string;
    get username(): string | undefined;
    get address(): string | undefined;
    get offlineSigner(): OfflineSigner | undefined;
    get walletNames(): string[];
    get walletCount(): number;
    get chainNames(): string[];
    get chainCount(): number;
    private get emitWalletName();
    private get emitChainName();
    private get emitViewOpen();
    getStargateClient: () => Promise<SigningStargateClient | undefined>;
    getCosmWasmClient: () => Promise<SigningCosmWasmClient | undefined>;
    setActions: (actions: Actions) => void;
    reset: () => void;
    private storeCurrent;
    setCurrentWallet: (walletName?: WalletName) => void;
    setCurrentChain: (chainName?: ChainName) => void;
    private getWallet;
    private get callbacks();
    connect: () => Promise<void>;
    disconnect: () => Promise<void>;
    openView: () => void;
    closeView: () => void;
}
